name: Inputs testing

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: 'do you need to be in quotes'
        required: true
        default: 'staging'
        type: choice
        options:
          - 'dev'
          - 'staging'
          - 'prod'

jobs:
  run-dev-smoke-test:
    if: ${{ inputs.log-level == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT in DEV
        run: echo  The input given is deployment for devs

  run-staging-smoke-test:
    if: ${{ inputs.log-level == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT in STAGING
        run: echo  The input given is deployment for staging

  run-prod-smoke-test:
    if: ${{ inputs.log-level == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT in PROD
        run: echo  The input given is deployment for production
