name: Inputs testing

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

jobs:
  run-environment-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT in DEV
        run: echo  The input given is deployment for devs
        if: ${{ inputs.logLevel }} == 'dev'
      - name: Print the input tag to STDOUT in STAGING
        run: echo  The input given is deployment for devs
        if: ${{ inputs.logLevel }} == 'staging'
      - name: Print the input tag to STDOUT in PROD
        run: echo  The input given is deployment for devs
        if: ${{ inputs.logLevel }} == 'prod'
