name: Inputs testing

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

jobs:
  if: ${{ inputs.logLevel }} == 'dev'
    print-tag:
      runs-on: ubuntu-latest
      steps:
        - name: Print the input tag to STDOUT
          run: echo  The input given is ${{ inputs.logLevel }}
  
  run-job:
    if: ${{ inputs.logLevel }} == 'dev'
      name: Print the input tag to STDOUT
        run: echo  The input given is ${{ inputs.logLevel }}