name: Test Branch Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  content: write
  pull-requests: write
  id-token: write

jobs:
  validate-app-with-tests:
    uses: ./github/workflows/validate-app.yml